-- Sales Analysis
-- 1. What is the total revenue generated by XYZ Retail Store?
Select sum(total_amount) Total_Revenue
From Orders;

-- 2. Which product category has generated the most revenue?
Select distinct category, sum(price) Total_Revenue
From Products
Group by category
Order by Total_Revenue Desc
Limit 1;

-- 3. What are the top 5 best-selling products based on quantity sold
Select pro.product_name, count(ord.quantity) Best_selling_Product
From products pro Join order_items ord
On pro.product_id = ord.product_id
Group by pro.product_name
Order by Best_selling_Product Desc
Limit 5;

-- Customer Insights
-- 1. How many unique customers have made purchases?
Select count(Distinct customer_id) as Unique_Customer
From orders;

-- 2. Which city has the highest number of customers?
Select city, count(customer_id) Highest_Customers
From customers
Group by city
Order by Highest_Customers Desc
Limit 1;

-- 3. What is the average age of customers?
Select avg(customer_id)
From customers;

-- Order Analysis
-- 1. How many orders have been placed in the last year?
Select count(order_id)
From orders;

-- 2. What is the average order value (total_amount)
Select avg(total_amount)
from orders;

-- 3. Which month has the highest total sales
Select ord.order_date, count(ords.order_id) Highest_Sales
From orders ord Join order_items ords
On ord.order_id = ords.order_id
Group by ord.order_date
Order by Highest_Sales Desc
limit 1;


-- Product Performance
-- 1. List all products that have never been sold.
Select pro.product_id, pro.product_name
From products pro Left Join order_items ord
On pro.product_id = ord.product_id
where ord.product_id Is Null;

-- 2. Identify the top 3 customers who have spent the most.
Select cus.customer_name, sum(ord.total_amount) Amount_Spent
From customers cus Join orders ord
On cus.customer_id = ord.customer_id
Group by cus.customer_name
Order by Amount_Spent Desc
Limit 3;

-- 3. Which product has the highest unit price?
Select pro.product_id, pro.product_name, max(ord.unit_price) Highest_unit_price
From products pro Join order_items ord
On pro.product_id = ord.product_id
Group by pro.product_id, pro.product_name
Order by  Highest_unit_price Desc
Limit 1;

-- Customer Segmentation
-- 1. Group customers by age range (e.g., 18-25, 26-35, etc.) and find the total revenue generated by each age group.
Select 
Case
When cus.age Between 18 and 25 Then '18-25'
When cus.age Between 26 and 35 Then '26-35'
When cus.age Between 36 and 45 Then '36-45'
When cus.age Between 46 and 55 Then '46-55'
When cus.age Between 56 and 65 Then '56-65'
Else '65+'
End Age_Range, sum(ord.total_amount) Total_revenue
From customers cus Join orders ord
On cus.customer_id = ord.order_id
Group by Age_Range 
Order by Total_revenue;

-- 2. Find the percentage of male and female customers.
Select gender, 
  Count(gender) AS Total_count, 
  Round(Count(gender) / (Select Count(gender) From customers) * 100, 2) AS percentage
From customers
Group by gender;




